### ISSUE TITLE
Last stage 

### ISSUE THREAD

**Issue by tpishz** [vsnz/TradingView-Webhook-Bot#16]
Hi i am on the last step, i have runned "python main.py" but it gives errors.

 `(TradingView-Webhook-Bot) [root@vps TradingView-Webhook-Bot]# python main.py
Traceback (most recent call last):
  File "main.py", line 36, in <module>
    serve(app, host='0.0.0.0', port=8080)
  File "/root/TradingView-Webhook-Bot/lib64/python3.6/site-packages/waitress/__init__.py", line 12, in serve
    server = _server(app, **kw)
  File "/root/TradingView-Webhook-Bot/lib64/python3.6/site-packages/waitress/server.py", line 88, in create_server
    sockinfo=sockinfo,
  File "/root/TradingView-Webhook-Bot/lib64/python3.6/site-packages/waitress/server.py", line 239, in __init__
    self.bind_server_socket()
  File "/root/TradingView-Webhook-Bot/lib64/python3.6/site-packages/waitress/server.py", line 368, in bind_server_socket
    self.bind(sockaddr)
  File "/root/TradingView-Webhook-Bot/lib64/python3.6/site-packages/waitress/wasyncore.py", line 398, in bind
    return self.socket.bind(addr)
OSError: [Errno 98] Address already in use`

I tried changing the ports to 8080, the hostname to my IP address, having no luck.
Please could you direct me in what to do next.

Thank You

**Comment by vsnz** [comment]
Hi,

You may serve something else already over port 80. Could be a webserver? Sadly TradingView only accepts either port 80 or 443 and you can't use any custom port.

**Comment by tpishz** [comment]
Hi, thank you for the reply. 

How do i uninstall this?
I would also like some advice, would you recommend I install it on a server without web such as cpanel, WHM, Apache in general?

**Comment by vsnz** [comment]
What do you want to uninstall? The websocket bot? Just remove the folder. `rm -rf <foldername>`

If Apache or any other service using port 80 it will most certainly interfere with the websocket bot. Which means you wont be able to use it. To check if the port is open / used run:

`sudo netstat -tnlp | grep :80`

**Comment by tpishz** [comment]
Thank you, I will definitely re install this when I get a clean server.
