### ISSUE TITLE
analytics.ff.avast.com:80

### ISSUE THREAD

**Issue by orinakal** [vsnz/TradingView-Webhook-Bot#20]
Hello again, my apologize if this a simple issue as i'm a little bit blind about coding and terminal

my terminal said "Serving on http://analytics.ff.avast.com:80"

i run in localhost with static ip ,  could you help me determine where i did wrong?

Thanks in advance!

**Comment by vsnz** [comment]
Hi,

Are you running the bot on your local machine/network?

**Comment by orinakal** [comment]
Yes. This is my latest result:

C:\Users\Fauzi\Desktop\tview>python main.py
Traceback (most recent call last):
  File "main.py", line 36, in <module>
    serve(app, host='0.0.0.0', port=80)
  File "C:\Users\Fauzi\AppData\Local\Programs\Python\Python38\lib\site-packages\waitress\__init__.py", line 12, in serve
    server = _server(app, **kw)
  File "C:\Users\Fauzi\AppData\Local\Programs\Python\Python38\lib\site-packages\waitress\server.py", line 81, in create_server
    last_serv = TcpWSGIServer(
  File "C:\Users\Fauzi\AppData\Local\Programs\Python\Python38\lib\site-packages\waitress\server.py", line 239, in init
    self.bind_server_socket()
  File "C:\Users\Fauzi\AppData\Local\Programs\Python\Python38\lib\site-packages\waitress\server.py", line 368, in bind_server_socket
    self.bind(sockaddr)
  File "C:\Users\Fauzi\AppData\Local\Programs\Python\Python38\lib\site-packages\waitress\wasyncore.py", line 398, in bind
    return self.socket.bind(addr)
OSError: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions

**Comment by vsnz** [comment]
Since you are running it on port 80 it requires admin/root privileges.

**Comment by orinakal** [comment]
Thanks, the port was'nt opened correctly.
Worked well after configuring my router..

**Comment by vsnz** [comment]
Glad to hear that it worked.
